//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSFAHASA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLNSFAHASAEntities : DbContext
    {
        public QLNSFAHASAEntities()
            : base("name=QLNSFAHASAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHD> CTHDs { get; set; }
        public virtual DbSet<DanhMucHinhThucThanhToan> DanhMucHinhThucThanhToans { get; set; }
        public virtual DbSet<DanhMucLoaiSanPham> DanhMucLoaiSanPhams { get; set; }
        public virtual DbSet<DonViTinh> DonViTinhs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<ThamSo> ThamSoes { get; set; }
    
        public virtual ObjectResult<TimKiem_Result> TimKiem(string tuKhoa)
        {
            var tuKhoaParameter = tuKhoa != null ?
                new ObjectParameter("TuKhoa", tuKhoa) :
                new ObjectParameter("TuKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiem_Result>("TimKiem", tuKhoaParameter);
        }
    }
}
